[project]
name = "kanairo"
version = "0.1.0"
description = "Classified adverts for Nairobians"
authors = ["Kanairo Team"]

dependencies = [
    "Django~=4.2.3",
    "dj-database-url~=2.0.0",
    "Pillow~=10.0.0",
]
