# Generated by Django 4.2.3 on 2023-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanairo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="slug",
            field=models.SlugField(default=0, max_length=4096),
            preserve_default=False,
        ),
    ]
