# Generated by Django 4.2.3 on 2023-08-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanairo", "0002_advert_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="advert",
            name="slug",
            field=models.SlugField(blank=True, max_length=4096),
        ),
    ]
